POST http://localhost:8080/api/v1/users/register
Content-Type: application/json 
Accept: application/json

{
    "email": "d@d.com",
    "name": "d",
    "role": "instructor"
}

###
POST http://localhost:8080/api/v1/users/register
Content-Type: application/json 
Accept: application/json

{
    "email": "c@c.com",
    "name": "c",
    "role": "instructor"
}

###
POST http://localhost:8080/api/v1/users/register
Content-Type: application/json 
Accept: application/json

{
    "email": "a@a.com",
    "name": "a",
    "role": "student"
}


###
POST http://localhost:8080/api/v1/users/register
Content-Type: application/json 
Accept: application/json

{
    "email": "b@b.com",
    "name": "b",
    "role": "student"
}


###
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json 
Accept: application/json

{
    "email": "d@d.com"
}

###
GET http://localhost:8080/api/v1/users/

###
GET http://localhost:8080/api/v1/users/64db2eccbf6f6512e4a23738

###
PATCH http://localhost:8080/api/v1/users/64db2ecbbf6f6512e4a23737
Accept: application/json
Content-Type: application/json

{
    "name": "a"
}

### 
DELETE http://localhost:8080/api/v1/users/64db2ecbbf6f6512e4a23737

### STUDENT
GET http://localhost:8080/api/v1/students/

### 
GET http://localhost:8080/api/v1/students/64db2ecdbf6f6512e4a23739

###
GET http://localhost:8080/api/v1/students/profile/

###
GET http://localhost:8080/api/v1/students/profile/64db2eccbf6f6512e4a23738

### INSTRUCTOR

GET http://localhost:8080/api/v1/instructors

###

GET http://localhost:8080/api/v1/instructors/64db2eccbf6f6512e4a23737

### CLASS

POST http://localhost:8080/api/v1/classes
Accept: application/json
Content-Type: application/json

{
    "name": "physics",
    "room": 10,
    "status": "scheduled",
    "schedule": "Tue Aug 17 2023 15:08:04 GMT+0700",
    "notes": "tentative"
}

###
POST http://localhost:8080/api/v1/classes
Accept: application/json
Content-Type: application/json

{
    "name": "math",
    "room": 9,
    "status": "scheduled",
    "schedule": "Tue Aug 17 2023 15:08:04 GMT+0700",
    "notes": "chance 100%"
}

###

POST http://localhost:8080/api/v1/classes
Accept: application/json
Content-Type: application/json

{
    "name": "science",
    "room": 8,
    "status": "scheduled",
    "schedule": "Tue Aug 17 2023 15:08:04 GMT+0700",
    "notes": null
}

###
GET http://localhost:8080/api/v1/classes

###
GET http://localhost:8080/api/v1/classes/64db3366eca84c838c9c8092

###

PUT http://localhost:8080/api/v1/classes/64db332f4372fa31dd77a678
Accept: application/json
Content-Type: application/json

{
    "name": "physics",
    "room": 10,
    "status": "ongoing",
    "schedule": "Tue Aug 17 2023 15:08:04 GMT+0700",
    "notes": "tentative"
}

###
DELETE http://localhost:8080/api/v1/classes/64db332f4372fa31dd77a678