POST http://localhost:8080/api/v1/users/register
Content-Type: application/json 
Accept: application/json

{
    "email": "d@d.com",
    "name": "d",
    "role": "instructor"
}

###
POST http://localhost:8080/api/v1/users/register
Content-Type: application/json 
Accept: application/json

{
    "email": "c@c.com",
    "name": "c",
    "role": "instructor"
}

###
POST http://localhost:8080/api/v1/users/register
Content-Type: application/json 
Accept: application/json

{
    "email": "a@a.com",
    "name": "a",
    "role": "student"
}


###
POST http://localhost:8080/api/v1/users/register
Content-Type: application/json 
Accept: application/json

{
    "email": "b@b.com",
    "name": "b",
    "role": "student"
}


###
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json 
Accept: application/json

{
    "email": "d@d.com"
}

###
GET http://localhost:8080/api/v1/users/

###
GET http://localhost:8080/api/v1/users/64dafc79f1628a03be1ebcf2

###
PATCH http://localhost:8080/api/v1/users/64dafc79f1628a03be1ebcf2
Accept: application/json
Content-Type: application/json

{
    "name": "a"
}

### 
DELETE http://localhost:8080/api/v1/users/64dafc79f1628a03be1ebcf2

### STUDENT
GET http://localhost:8080/api/v1/students/

### 
GET http://localhost:8080/api/v1/students/64dafc7bf1628a03be1ebcf3

###
GET http://localhost:8080/api/v1/students/profile/

###
GET http://localhost:8080/api/v1/students/profile/64dafc79f1628a03be1ebcf2

### INSTRUCTOR

GET http://localhost:8080/api/v1/instructors

###

GET http://localhost:8080/api/v1/instructors/64dafcacf1628a03be1ebcf4
