POST http://localhost:8080/api/v1/users/register
Content-Type: application/json 
Accept: application/json

{
    "email": "d@d.com",
    "name": "d",
    "role": "instructor"
}

###
POST http://localhost:8080/api/v1/users/register
Content-Type: application/json 
Accept: application/json

{
    "email": "a@a.com",
    "name": "a",
    "role": "student"
}

###
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json 
Accept: application/json

{
    "email": "d@d.com"
}

###
GET http://localhost:8080/api/v1/users/

###
GET http://localhost:8080/api/v1/users/64d98113b99e9a59a18e23eb

###
PATCH http://localhost:8080/api/v1/users/64d98113b99e9a59a18e23eb
Accept: application/json
Content-Type: application/json

{
    "name": "a"
}

### 
DELETE http://localhost:8080/api/v1/users/64d88a20862d436d26326484

###
GET http://localhost:8080/api/v1/students/

### 
GET http://localhost:8080/api/v1/students/64da2df80fd929d114b9797d

###
GET http://localhost:8080/api/v1/students/profile/

###
GET http://localhost:8080/api/v1/students/profile/64da2df80fd929d114b9797d